[build]
  # Directory to publish
  publish = "build"
  
  # Build command
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Optimize build
  NPM_FLAGS = "--production=false"

# Redirects for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables for demo mode
[context.production.environment]
  REACT_APP_DEMO_MODE = "true"
  REACT_APP_VERSION = "2.0.0"
  
[context.deploy-preview.environment]
  REACT_APP_DEMO_MODE = "true"
  REACT_APP_VERSION = "2.0.0-preview"
